[package]
name = "progress-token"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["sync"] }
tokio-util = "0.7.14"
uuid = { version = "1.16.0", features = ["v4"] }
